name: chromium
adopt-info: chromium
summary: Chromium web browser, open-source version of Chrome
description: |
 An open-source browser project that aims to build a safer, faster, and more
 stable way for all Internet users to experience the web.
confinement: strict
base: core20
assumes:
  - snapd2.55 # >=2.55 needed for the cups interface
compression: lzo

apps:
  chromium:
    extensions: [gnome-3-38]
    command: bin/chromium.launcher
    desktop: bin/chromium.desktop
    common-id: chromium-browser.desktop
    environment:
      CHROME_DESKTOP: chromium.desktop
      CHROME_CONFIG_HOME: $SNAP_USER_COMMON
      GTK_USE_PORTAL: 1
      SPA_PLUGIN_DIR: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/spa-0.2
      PIPEWIRE_CONFIG_NAME: $SNAP/usr/share/pipewire/pipewire.conf
      PIPEWIRE_MODULE_DIR: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pipewire-0.3
    plugs:
      - audio-playback
      - audio-record
      - bluez # for Web Bluetooth (https://launchpad.net/bugs/1887201)
      - camera
      - cups
      - home
      - joystick
      - mount-observe
      - network
      - network-manager
      - password-manager-service
      - raw-usb # for WebUSB (https://launchpad.net/bugs/1780678)
      - removable-media
      - screen-inhibit-control
      - system-packages-doc
      - u2f-devices
      - unity7 # required for xdg-open to work
      - upower-observe
    slots:
      - mpris
  chromedriver:
    extensions: [gnome-3-38]
    command: usr/lib/chromium-browser/chromedriver
    plugs:
      - network-bind
      # + all the plugs required by chromium, so that when chromedriver
      # executes chromium it inherits the correct set of permissions
      - audio-playback
      - audio-record
      - bluez
      - camera
      - cups
      - home
      - joystick
      - mount-observe
      - network
      - network-manager
      - password-manager-service
      - raw-usb
      - removable-media
      - screen-inhibit-control
      - system-packages-doc
      - u2f-devices
      - unity7
      - upower-observe
    slots:
      - mpris

plugs:
  # This is not used or needed for anything other than to trigger automatic
  # installation of the cups snap via "default-provider: cups"
  foo-install-cups:
    interface: content
    content: foo
    default-provider: cups
    target: $SNAP_DATA/foo
  browser-sandbox:
    interface: browser-support
    allow-sandbox: true
  chromium-config:
    interface: personal-files
    read: [$HOME/.config/chromium, $HOME/.chromium-browser.init]
  etc-chromium-browser-policies:
    interface: system-files
    read: [/etc/chromium-browser/policies]

layout:
  /usr/lib/man-db:
    bind: $SNAP/usr/lib/man-db
  /usr/share/libdrm:
    bind: $SNAP/gnome-platform/usr/share/libdrm

parts:
  # Launchpad builders have a timeout for how long they are allowed to access
  # the internet (through a proxy) starting from the start of the build.
  # Since the chromium part takes a long time to build, we need to ensure
  # that all other parts that need to access the internet (to e.g. fetch build
  # or stage packages) are built before it (before the proxy authentication is
  # revoked).

  chromium-build:
    plugin: dump
    source: build
    organize:
      '*' : build/
    override-prime: ""

  chromium:
    plugin: nil
    source: https://commondatastorage.googleapis.com/chromium-browser-official/chromium-114.0.5735.90.tar.xz
    source-checksum: sha512/7a5eb6bbf0e25f1bbdd63dd860ba96da3052b3967d04364b60265ee588ffcd7b9e90ea93009e52f3228128950988327a087447c6d12db61e66f518850097c8af
    after:
      - chromium-build
      - launcher
      - manpage
      - pipewire
      - va-drivers
      - libva
    build-packages:
      - chrpath
      - default-jre-headless
      - elfutils
      - g++
      - git
      - gperf
      - gzip
      - libasound2-dev
      - libcap-dev
      - libcups2-dev
      - libcurl4-openssl-dev
      - libevdev-dev
      - libffi-dev
      - libicu-dev
      - libkrb5-dev
      - libnss3-dev
      - libpam0g-dev
      - libpci-dev
      - libssl-dev
      - libsystemd-dev
      - libwayland-dev
      - libxshmfence-dev
      - libxss-dev
      - lsb-release
      - make
      - mesa-common-dev
      - ninja-build
      - python3-pkg-resources
      - python3-xcbgen
      - quilt
      - qtbase5-dev
      - sed
      - subversion
      - wget
      - xcb-proto
      - yasm
    stage-packages:
      - libnss3
      - libxss1
    override-pull: |
      set -eux
      snapcraftctl pull
      . chrome/VERSION
      snapcraftctl set-version "$MAJOR.$MINOR.$BUILD.$PATCH"
    override-build: |
      set -eux

      QUILT_PATCHES=$SNAPCRAFT_STAGE/build/chromium-patches QUILT_PC=.pc.chromium-patches quilt push -a

      # Fetch the dirmd executable from Google's servers
      # (it is not included in the source tarball).
      ./third_party/depot_tools/dirmd help
      [ -x ./third_party/depot_tools/.cipd_bin/dirmd ]

      # Get the Node.js binaries needed to build chromium's WebUI
      third_party/node/update_node_binaries

      # Generate qt_shim_moc.cc with our moc or it fails to build with
      # Focal's version of Qt.
      moc ui/qt/qt_shim.h > ui/qt/qt_shim_moc.cc

      # Pre-built binaries are provided for clang on x86-64,
      # for all other architectures they have to be built from source.
      if [ $SNAPCRAFT_TARGET_ARCH = "amd64" ]; then
        python3 tools/clang/scripts/update.py
      else
        # Building clang requires a version of cmake newer than what's in
        # focal. Fetch it and build it from source.
        CMAKE_VERSION=3.18.1
        wget -O - https://github.com/Kitware/CMake/releases/download/v$CMAKE_VERSION/cmake-$CMAKE_VERSION.tar.gz | tar -x -z
        cd cmake-$CMAKE_VERSION
        ./bootstrap --prefix=/usr
        make -j$SNAPCRAFT_PARALLEL_BUILD_COUNT install
        cd ..

        # Fetch and build clang from source.
        python3 tools/clang/scripts/build.py --skip-build --without-android --without-fuchsia
        # --with-ml-inliner-model= to avoid depending on vpython3,
        # https://bugs.chromium.org/p/chromium/issues/detail?id=1368071
        python3 tools/clang/scripts/build.py --skip-checkout --bootstrap --disable-asserts --pgo --without-android --without-fuchsia --gcc-toolchain=/usr --use-system-cmake --with-ml-inliner-model=
      fi

      # Build GN
      export CXX=$PWD/third_party/llvm-build/Release+Asserts/bin/clang++
      export AR=$PWD/third_party/llvm-build/Release+Asserts/bin/llvm-ar
      cp tools/gn/bootstrap/last_commit_position.h tools/gn/src/
      python3 tools/gn/bootstrap/bootstrap.py --skip-generate-buildfiles

      # Build chromium
      OUT=out/Release
      mkdir -p $OUT
      cp $SNAPCRAFT_STAGE/build/args.gn $OUT/
      if [ $SNAPCRAFT_TARGET_ARCH = "armhf" ] || [ $SNAPCRAFT_TARGET_ARCH = "arm64" ]; then
        # Workaround for ENOENT: no such file or directory,
        # 'gen/ui/webui/resources/tsc/cr_components/history_clusters/history_clusters_shared_style.css.js
        echo "optimize_webui = false" >> $OUT/args.gn
      fi
      if [ $SNAPCRAFT_TARGET_ARCH = "armhf" ]; then
        # Do not use lld (the LLVM linker) on 32-bits architectures
        # (armhf) because it OOMs when linking the chrome binary
        echo "use_lld = false" >> $OUT/args.gn
        # Do not build with ThinLTO either, because it requires lld
        echo "use_thin_lto = false" >> $OUT/args.gn
        # Do not build with NEON on armhf (https://launchpad.net/bugs/1884856)
        echo "arm_use_neon = false" >> $OUT/args.gn
      fi

      # Temporary workaround to ensure that version 2.4.107 of libdrm from
      # focal-updates is used instead of version 2.4.105 from the gnome
      # platform snap, until it is rebuilt with the updated version. This is
      # because dri.pc (from mesa-common-dev) comes from the archive, not from
      # the gnome platform snap.
      cd /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pkgconfig
      ln -fs libdrm.pc libdrm-uninstalled.pc
      cd -

      $OUT/gn gen $OUT
      ninja -C $OUT chrome chrome_sandbox chromedriver

      # Strip debug symbols off the chrome binary
      eu-strip $OUT/chrome

      # Install to $SNAPCRAFT_PART_INSTALL
      mkdir -p $SNAPCRAFT_PART_INSTALL
      cp chrome/app/theme/chromium/linux/product_logo_256.png $SNAPCRAFT_PART_INSTALL/chromium.png
      T=$SNAPCRAFT_PART_INSTALL/usr/lib/chromium-browser
      mkdir -p $T
      cd $OUT
      cp chrome chromedriver chrome_crashpad_handler \
          chrome_*.pak resources.pak \
          icudtl.dat \
          libEGL.so libGLESv2.so libffmpeg.so \
          libvk_swiftshader.so libvulkan.so.1 vk_swiftshader_icd.json \
          v8_context_snapshot.bin \
          $T/
      cp chrome_sandbox $T/chrome-sandbox
      mkdir $T/locales
      cp locales/*.pak $T/locales/
      if [ -d swiftshader ]; then
        # not built on arm*
        mkdir $T/swiftshader
        cp swiftshader/*.so $T/swiftshader/
      fi

      # Fix setuid bits on the sandbox executable
      # (ref: https://forum.snapcraft.io/t/call-for-testing-chromium-snap/1714/16)
      chmod 4555 $SNAPCRAFT_PART_INSTALL/usr/lib/chromium-browser/chrome-sandbox

      # Generate and install the man page (see the "manpage" part)
      mkdir -p $SNAPCRAFT_PART_INSTALL/man1
      sed \
          -e "s/@@PACKAGE@@/chromium/g" \
          -e "s/@@MENUNAME@@/chromium/g" \
          -e "s:\$HOME/.config:\$SNAP_USER_DATA/.config:g" \
          -e "s:\$HOME/.cache:\$SNAP_USER_COMMON/.cache:g" \
          $SNAPCRAFT_PART_SRC/chrome/app/resources/manpage.1.in \
          > $SNAPCRAFT_PART_INSTALL/man1/chrome.1
      gzip -9n $SNAPCRAFT_PART_INSTALL/man1/chrome.1
    stage:
      - -usr/lib/*/libsecret-*
    prime:
      - -etc/init.d
      - -etc/xdg
      - -usr/include
      - -usr/share/doc
      - -usr/share/lintian
      - -usr/share/man

  launcher:
    plugin: dump
    source: launcher
    organize:
      '*': bin/

  firstrun:
    plugin: dump
    source: firstrun
    organize:
      '*': firstrun/

  tests:
    plugin: dump
    source: tests
    organize:
      '*': tests/

  # Stage packages required for the "man" binary, which is invoked when
  # chromium is called with the "-h" (or "--help") argument
  # (see https://launchpad.net/bugs/1848083).
  manpage:
    plugin: nil
    stage-packages:
      - groff-base
      - libgdbm6
      - libpipeline1
      - man-db
    prime:
      - -etc
      - -usr/lib/tmpfiles.d
      - -usr/share/bug
      - -usr/share/calendar
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/lintian
      - -usr/share/man
      - -usr/share/man-db
      - -var

  # Create a symlink xdg-email -> xdg-open, as the latter is perfectly able to
  # handle mailto: URLs (see https://launchpad.net/bugs/1849774).
  # xdg-open is a wrapper provided by the core snap.
  xdg-email:
    plugin: nil
    override-pull: ""
    override-prime: |
      set -eux
      mkdir -p usr/bin
      cd usr/bin
      ln -s /usr/bin/xdg-open xdg-email

  libsecret:
    source: https://gitlab.gnome.org/GNOME/libsecret.git
    source-depth: 1
    source-tag: '0.20.5'
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Dgtk_doc=false
      - -Dmanpage=false
      - -Dgcrypt=false  # https://gitlab.gnome.org/GNOME/libsecret/-/issues/49
    stage:
      - usr/lib/*/libsecret-*

  libva:
    source: https://github.com/intel/libva/archive/refs/tags/2.17.0.tar.gz
    plugin: meson # Because autotools makes a mess of this.
    meson-parameters:
      - --prefix=/usr
    build-packages:
      - pkg-config
      - libdrm-dev
      - xorg-dev
      - libxcb-dri3-dev
      - libgl1-mesa-dev
      - libgl1-mesa-glx
      - libwayland-dev

  # VA-API drivers for HW-accelerated video decoding
  va-drivers:
    plugin: nil
    stage-packages:
      - mesa-va-drivers
      - on amd64:
        - i965-va-driver
        - intel-media-va-driver
    stage:
      - usr/lib/*/dri/*_video.so

  # PipeWire
  pipewire:
    source: https://gitlab.freedesktop.org/pipewire/pipewire/-/archive/0.3.32/pipewire-0.3.32.tar.gz
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      - --strip
      - -Dalsa=disabled
      - -Dpipewire-alsa=disabled
      - -Djack=disabled
      - -Dpipewire-jack=disabled
      - -Dsession-managers=[]
    prime:
      - usr/lib/*/pipewire-*
      - usr/lib/*/spa-*
      - usr/lib/*/libpipewire*.so*
      - usr/share/pipewire
