#!/usr/bin/python3
# -*- coding: utf-8 -*-

import os.path
from selenium import webdriver

import gi
gi.require_version("Snapd", "1")
from gi.repository import Snapd

if __name__ == '__main__':
    options = webdriver.chrome.options.Options()
    options.binary_location = "/snap/chromium/current/command-chromium.wrapper"
    options.add_argument("headless")
    driver_path = "/snap/bin/chromium.chromedriver"
    driver = webdriver.Chrome(executable_path=driver_path, options=options)
    try:
        version = driver.capabilities['browserVersion']
    except KeyError:
        version = driver.capabilities['version']

    client = Snapd.Client()
    snap = client.get_snap_sync("chromium")
    assert snap.get_version() == version

    tests_dir = os.path.dirname(os.path.realpath(__file__))
    driver.get("file://{}/data/chromium-version.html".format(tests_dir))
    assert driver.find_element_by_id("chromium_version").text == version

    driver.quit()
